require: rubocop-performance

Style/EndOfLine:
  EnforcedStyle: lf

Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30
